### ISSUE TITLE
Синхронизировать окончание закачки с появлением соответствующего сообщения

### ISSUE THREAD

**Issue by Zey-Uzh** [IngvarJackal/FurView2#102]
Сейчас после появления сообщения о готовности приложение ещё продолжает скачивание.
Это потому что скачивание идёт через асинхронные задачи. Необходимо согласовать окончание закачки с появлением сообщения. Для этого  логику придётся переписать. На даный момент разблокировка и показываз картинки когда отрабатывают встроенные методы, а не асинхронный код UIL.

**Comment by IngvarJackal** [comment]
Изменил немного интерфейс драйвера чтобы можно было отслеживать скачивание изображений: https://github.com/IngvarJackal/FurView2/pull/107

**Comment by Zey-Uzh** [comment]
Доделано в том же https://github.com/IngvarJackal/FurView2/pull/107 , но всё же надо потом подумать как оптимизировать.
