### ISSUE TITLE
Невозможно пролистать дальше 23 страницы результатов поиска

### ISSUE THREAD

**Issue by connertech** [IngvarJackal/FurView2#106]
ветка: dev
версия: f0553ea95b6944a52507ceb33feb812275c8428c
Сабж.
Примечание: если за время просмотра на сайт успели залить еще изображения с искомым тэгом, можно пролистать чуть дальше, при этом последняя страница может быть неполной.

**Comment by IngvarJackal** [comment]
не воспроизводится
