### ISSUE TITLE
Найти прокси для доступа к e621

### ISSUE THREAD

**Issue by Zey-Uzh** [IngvarJackal/FurView2#17]

**Comment by Zey-Uzh** [comment]
Экспериментирую с http://foxtools.ru/Proxy , его  API http://api.foxtools.ru/v2/Help/Proxy и функцией андроида http://developer.android.com/reference/android/net/Proxy.html

**Comment by IngvarJackal** [comment]
@Zey-Uzh я сделал использование прокси и даже впихнул кнопку, лол. Теперь напиши [селектор](https://github.com/IngvarJackal/FurView2/blob/master/app/src/main/java/ru/furry/furview2/system/ProxySettings.java#L8), ибо они быстро протухают.

**Comment by Zey-Uzh** [comment]
- Перекинуть адрес сайта с проксями в init селектора.
  Текущие задачи:
- Сделать сортировку по отклику.
- Сделать проверку доступности e621
- Передать массив из ProxyItem в mainActivity 
  https://github.com/IngvarJackal/FurView2/blob/master/app/src/main/java/ru/furry/furview2/MainActivity.java#L113 
  https://github.com/IngvarJackal/FurView2/blob/master/app/src/main/java/ru/furry/furview2/FullscreenActivity.java#L23
- Возможно сделать переключение между найденными прокси в случае если пользователя не устраивает скорость.

**Comment by IngvarJackal** [comment]
Я начал использовать e621 потому что у е926 истёк сертификат

**Comment by Zey-Uzh** [comment]
Commit https://github.com/IngvarJackal/FurView2/commit/b847fa97ad7005d8f52a7d8f101e03ba10f7e3f9

Сделано:
- Запрос прокси
- Парсер списка прокси
- Обработка отсутствия интернета
- Выборка быстрейшей прокси из полученных
- Установка прокси
