### ISSUE TITLE
Прокси: автоматический подбор, тестирование и замена

### ISSUE THREAD

**Issue by IngvarJackal** [IngvarJackal/FurView2#31]
Прокси нужно автоматически менять. Тестировать прокси специально не нужно -- просто выставить таймауты на соединение.
Нужно будет обеспечить system-wide замену с помощью класса-синглтона чтобы менять прокси всякий раз, как он ломается или недоступен.
Нужно оптимизировать поиск прокси чтобы он выполнялся как можно быстрее.

**Comment by IngvarJackal** [comment]
см. #17

**Comment by Zey-Uzh** [comment]
Слияние в ветку ProxySelector3 обновлённой ветки master: 5a9281e14bceb3817dc7cdfc58cf781c081b58a6
После слиянии не нашёл где именно надо устанавливать прокси. Пока только сама проверка.
В https://github.com/IngvarJackal/FurView2/commit/5a9281e14bceb3817dc7cdfc58cf781c081b58a6#diff-906cb354c33f4241314bce2be2adcbcaR123 и https://github.com/IngvarJackal/FurView2/commit/5a9281e14bceb3817dc7cdfc58cf781c081b58a6#diff-906cb354c33f4241314bce2be2adcbcaR147 похоже надо применить http://forum.startandroid.ru/viewtopic.php?f=30&t=1870

**Comment by IngvarJackal** [comment]
![alt text](http://s4.postimg.org/ml11b9zcd/scheme.png)
