### ISSUE TITLE
Дополнительные прокси

### ISSUE THREAD

**Issue by IngvarJackal** [IngvarJackal/FurView2#36]
Нужно добавить возможность установки своего прокси и использования прокси Opera Mini. см #6

**Comment by IngvarJackal** [comment]
Ещё нужно добавить HTTPS proxy.antizapret.prostovpn.org:3143 из http://antizapret.prostovpn.org/proxy.pac

**Comment by Zey-Uzh** [comment]
Сделано всё, кроме прокси Opera. При случае найти ip/port прокси оперы и доделать.

**Comment by IngvarJackal** [comment]
Опера не использует http прокси. У неё свой формат обмена данными, как говорит @connertech

**Comment by Zey-Uzh** [comment]
Опера удалена в https://github.com/IngvarJackal/FurView2/pull/108
