### ISSUE TITLE
Вставка тэгов по нажатию на них

### ISSUE THREAD

**Issue by IngvarJackal** [IngvarJackal/FurView2#37]
В FullscreenActivity в строку поиска.

**Comment by IngvarJackal** [comment]
не работает в dev!!

**Comment by Zey-Uzh** [comment]
Исправлено в https://github.com/IngvarJackal/FurView2/pull/87

**Comment by userow** [comment]
Проверено. Присутствует в ветке DescriptionInFullscreen
