### ISSUE TITLE
FullscreenActivity: ограничения длины полей

### ISSUE THREAD

**Issue by IngvarJackal** [IngvarJackal/FurView2#46]
чтобы надписи не вылезали, их нужно обрезать.

**Comment by Zey-Uzh** [comment]
Ветка с изменениями слита с dev

**Comment by connertech** [comment]
Результат отвратительный. Во-первых, на e621 полно тэгов, отличающихся только концовками. Во-вторых, доля тэгов, которые не укладываются в отведенную ширину, весьма велика. Хрен с ним, с красивым форматированием текста, но пускай лучше я буду видеть все тэги целиком, без этих стыдливых многоточий. Старый вариант устраивал полностью.
Пример отображения на моем телефоне: http://bit.ly/1JoANpl

**Comment by IngvarJackal** [comment]
можно уменьшить число тэгов на 1 в строке

**Comment by Zey-Uzh** [comment]
Уменьшено в https://github.com/IngvarJackal/FurView2/pull/116
В портретном положении 4 тэга в строке, по 12 символов.
В альбомном положении 6 тэгов в строке, по 12 символов.

Если есть предложения получше - переоткрывайте задачу)
