### ISSUE TITLE
Сохранение настроек

### ISSUE THREAD

**Issue by IngvarJackal** [IngvarJackal/FurView2#48]
Нужно сохранять пользовательские настройки прокси и иже при повороте и при выключении приложения. см. #33

**Comment by Zey-Uzh** [comment]
Сделано https://github.com/IngvarJackal/FurView2/commit/15edbcf8d219e448660ebb7e06e48c2542be2c1b

**Comment by Zey-Uzh** [comment]
Ещё не протестировано при повороте экрана.
