### ISSUE TITLE
Реализация прокси Антизапрета

### ISSUE THREAD

**Issue by Zey-Uzh** [IngvarJackal/FurView2#49]
Реализовать использование http://antizapret.prostovpn.org/

**Comment by Zey-Uzh** [comment]
Сначала сделать https://github.com/IngvarJackal/FurView2/issues/50

**Comment by IngvarJackal** [comment]
ИМХО, можно юзать proxy.antizapret.prostovpn.org:3143 до реализации #50 из-за **крайней** важности прокси для дальнейшего развития проекта.
