### ISSUE TITLE
proxy.antizapret.prostovpn.org

### ISSUE THREAD

**Issue by IngvarJackal** [IngvarJackal/FurView2#55]
прокси с антизапретом работает только для сайтов, запрещённый в реестре роскомнадзора.

**Comment by Zey-Uzh** [comment]
https://github.com/IngvarJackal/FurView2/tree/ParsingPAC
Сделано:
- Проверка ip адреса галереи по списке запрещённых сайтов от Антизапрета;
- Установка прокси выдернутого из *.pac файла от Антизапрета;

**Comment by IngvarJackal** [comment]
а закрывать кто будет?
