### ISSUE TITLE
Алиасы

### ISSUE THREAD

**Issue by IngvarJackal** [IngvarJackal/FurView2#57]
добавить возможность создавать локальные алиасы вроде male/male -> gay

**Comment by Zey-Uzh** [comment]
Сюда же Чёрный список для тэгов/авторов
https://github.com/IngvarJackal/FurView2/issues/70

**Comment by IngvarJackal** [comment]
см. также #68

**Comment by Zey-Uzh** [comment]
Реализовано до конца в https://github.com/IngvarJackal/FurView2/issues/129
