### ISSUE TITLE
Блокировка UI во время поиска/проверки прокси

### ISSUE THREAD

**Issue by Zey-Uzh** [IngvarJackal/FurView2#64]
Так и не реализовал блокировку UI. Необходимо доделать.

**Comment by IngvarJackal** [comment]
Это не баг.

**Comment by Zey-Uzh** [comment]
Стараюсь сделать здесь
https://github.com/IngvarJackal/FurView2/pull/72

**Comment by Zey-Uzh** [comment]
Доделано в https://github.com/IngvarJackal/FurView2/pull/75

**Comment by Zey-Uzh** [comment]
Закончено, ветка слита в dev
