### ISSUE TITLE
FulscreenActivity: полноэкранный режим

### ISSUE THREAD

**Issue by IngvarJackal** [IngvarJackal/FurView2#90]
Сделать полноэкранный режим по нажатию кнопки. И убарть padding чтобы у картинки белых полосок не было.

**Comment by IngvarJackal** [comment]
И фон при переходе в полноэкранный режим делать чёрным.

**Comment by Zey-Uzh** [comment]
Как-то внезапно сделал в https://github.com/IngvarJackal/FurView2/pull/87

**Comment by userow** [comment]
Проверено. Присутствует в ветке DescriptionInFullscreen
