### ISSUE TITLE
Не отображаются некоторые картинки в полноэкранном режиме

### ISSUE THREAD

**Issue by Zey-Uzh** [IngvarJackal/FurView2#91]
Например https://e621.net/post/show/703495/azzy-cat-cosplay-crossdressing-duo-feline-gatling_ (найти в приложении можно по автору pawzors)
Причём данное изображение отображается в  миниатюре в MainActivity. А вот в FullscreenActivity не отображается, хотя тэги, рейтинг, автора цепляет и показывает
Возможно слишком большой размер... пока не понятно.

**Comment by IngvarJackal** [comment]
У меня эта картинка вполне себе открывается.

**Comment by connertech** [comment]
У меня открывается. Вероятно, был слишком долгий ответ прокси. У меня и превьюшки не все отображаются, если прокси тупит.

**Comment by IngvarJackal** [comment]
либо места мало было на карте, потому не вышло сохранить. закрываю по невоспроизводимости.
