### ISSUE TITLE
Форматирование текста описания

### ISSUE THREAD

**Issue by Zey-Uzh** [IngvarJackal/FurView2#92]
Текст описания картинки необходимо отформатировать и убрать из него служебные тэги. Причём делать это нужно ещё в драйвере https://github.com/IngvarJackal/FurView2/blob/dev/app/src/main/java/ru/furry/furview2/drivers/e621/DriverE621.java#L190

**Comment by Zey-Uzh** [comment]
Сделано в https://github.com/IngvarJackal/FurView2/pull/103

**Comment by IngvarJackal** [comment]
@Zey-Uzh закрывать надо :)
