### ISSUE TITLE
Не работает кнопка поиска на экранной клавиатуре на странице просмотра изображения

### ISSUE THREAD

**Issue by connertech** [IngvarJackal/FurView2#94]
Ветка: dev
Версия: d70c80ab4eaf8acde2c07536f70c2f2a82ca499a
Изменения, сделанные в 1d399a4a08c6da0d8c5b498e0bad8fdd084b7bdc , работают на стартовой странице и странице результатов поиска, но не коснулись страницы результатов просмотра. Там по-прежнему вместо кнопки "поиск" на клавиатуре показывается кнопка "далее", для поиска приходится нажимать кнопку на странице рядом с полем ввода, а клавиатуру скрывать отдельным действием.

**Comment by Zey-Uzh** [comment]
Работает в https://github.com/IngvarJackal/FurView2/commit/f97fcc8512b070c5cb3c8b2ce74b48bd470e598a
Как только будет мердж https://github.com/IngvarJackal/FurView2/pull/87 с dev, то заработает и в dev

**Comment by IngvarJackal** [comment]
Ты дожен приассигнить себя на этот баг
